# Generated by Django 4.1.3 on 2022-11-23 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='テストID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('category', models.CharField(max_length=10, verbose_name='カテゴリー')),
                ('author', models.CharField(max_length=20, verbose_name='著者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
